shows = [
    {"id": 482, "title": "F**KFACE Break Show", "slug": "f-kface-break-show"},
    {"id": 349, "title": "Funhaus Live", "slug": "funhaus-live"},
    {"id": 327, "title": "Face Jam", "slug": "face-jam"},
    {"id": 495, "title": "The Dogbark Podcast", "slug": "the-dogbark-podcast"},
    {"id": 22, "title": "Let's Play", "slug": "lets-play"},
    {"id": 63, "title": "Gameplay", "slug": "gameplay"},
    {"id": 438, "title": "Funhaus Unfiltered", "slug": "funhaus-unfiltered"},
    {"id": 369, "title": "F**KFACE", "slug": "f-kface"},
    {"id": 474, "title": "Dog Pound Exclusives", "slug": "the-vault-members-only"},
    {
        "id": 486,
        "title": "Are You Fucking Kidding Me",
        "slug": "are-you-fucking-kidding-me",
    },
    {"id": 492, "title": "Dogbark", "slug": "dogbark"},
    {"id": 431, "title": "Grotethe", "slug": "tales-from-the-stinky-dragon"},
    {"id": 457, "title": "30 Morbid Minutes", "slug": "thirty-morbid-minutes"},
    {"id": 485, "title": "So...Alright", "slug": "so-alright"},
    {"id": 498, "title": "Trash for Trash", "slug": "trash-4-trash"},
    {"id": 483, "title": "Hypothetical Nonsense", "slug": "hypothetical-nonsense"},
    {"id": 69, "title": "Rooster Teeth Podcast", "slug": "rt-podcast"},
    {"id": 467, "title": "Does it Do?", "slug": "does-it-do"},
    {"id": 379, "title": "Red Web", "slug": "red-web"},
    {"id": 462, "title": "ANMA Podcast", "slug": "anma-podcast"},
    {"id": 490, "title": "Best Friends Simulator", "slug": "best-friends-simulator"},
    {"id": 489, "title": "Best Friends TV", "slug": "best-friends-tv"},
    {"id": 488, "title": "Let's Build", "slug": "let-s-build"},
    {"id": 503, "title": "Inside Gaming Extras", "slug": "inside-gaming-extras"},
    {"id": 132, "title": "Camp Camp", "slug": "camp-camp"},
    {"id": 145, "title": "DEATH BATTLE Cast", "slug": "death-battle-cast"},
    {"id": 506, "title": "Red Web: Book Club", "slug": "red-web-book-club"},
    {
        "id": 504,
        "title": "Definitely Not a Talk Show",
        "slug": "definitely-not-a-talk-show",
    },
    {"id": 497, "title": "Dogbark Plays", "slug": "dogbark-plays"},
    {"id": 487, "title": "LvL Up", "slug": "lvl-up"},
    {"id": 355, "title": "RTTV Specials", "slug": "rttv-specials"},
    {"id": 502, "title": "Stinky Dragon Shorts", "slug": "stinky-dragon-shorts"},
    {"id": 494, "title": "Mini-Series", "slug": "mini-series"},
    {
        "id": 499,
        "title": "Stinky Dragon Adventures",
        "slug": "stinky-dragon-adventures",
    },
    {"id": 81, "title": "Funhaus Variety!", "slug": "funhaus-shorts"},
    {"id": 229, "title": "Board as Hell", "slug": "board-as-hell"},
    {"id": 469, "title": "Red Web: Case Files", "slug": "red-web-case-files"},
    {"id": 137, "title": "Always Open", "slug": "always-open"},
    {"id": 120, "title": "Inside Gaming Roundup", "slug": "news-roundups"},
    {
        "id": 218,
        "title": "Death Battle With Commentary",
        "slug": "death-battle-with-commentary",
    },
    {"id": 237, "title": "Death Battle Bloopers", "slug": "death-battle-bloopers"},
    {"id": 28, "title": "RT Recap", "slug": "rt-recap"},
    {"id": 94, "title": "DEATH BATTLE!", "slug": "death-battle"},
    {"id": 62, "title": "Funhaus Podcast", "slug": "funhaus-podcast"},
    {"id": 475, "title": "Please Be Nice To Me", "slug": "please-be-nice-to-me"},
    {
        "id": 114,
        "title": "DEATH BATTLE Fight Previews",
        "slug": "death-battle-previews",
    },
    {"id": 481, "title": "RWBY VTubing", "slug": "rwby-vtubing"},
    {"id": 213, "title": "Songs About Games", "slug": "songs-about-games"},
    {"id": 460, "title": "Must Be Dice", "slug": "must-be-dice"},
    {"id": 401, "title": "Extra Life", "slug": "extra-life"},
    {"id": 496, "title": "F**kface Off", "slug": "f-kface-off"},
    {"id": 394, "title": "Recreyo", "slug": "recreyo"},
    {"id": 493, "title": "Infinights", "slug": "infinights"},
    {"id": 491, "title": "Demo Wheel", "slug": "demo-wheel"},
    {"id": 53, "title": "On The Spot", "slug": "on-the-spot"},
    {"id": 34, "title": "A Simple Walk ", "slug": "a-simple-walk"},
    {
        "id": 211,
        "title": "Five Nights at Freddy's Songs",
        "slug": "five-nights-at-freddy-s-songs",
    },
    {"id": 6, "title": "Achievement Hunter", "slug": "achievement-hunter"},
    {
        "id": 87,
        "title": "Off Topic",
        "slug": "off-topic-the-achievement-hunter-podcast",
    },
    {"id": 184, "title": "Between the Games", "slug": "between-the-games"},
    {"id": 323, "title": "Let's Roll", "slug": "let-s-roll"},
    {"id": 452, "title": "Challenge Accepted", "slug": "challenge-accepted"},
    {"id": 164, "title": "AH Animated", "slug": "ah-animated"},
    {"id": 43, "title": "Play Pals", "slug": "play-pals"},
    {"id": 197, "title": "Off Topic: Last Call", "slug": "last-call"},
    {"id": 439, "title": "FIRST Play", "slug": "let-s-firt"},
    {
        "id": 318,
        "title": "Best of Achievement Hunter",
        "slug": "best-of-achievement-hunter",
    },
    {"id": 253, "title": "Kinda Funny Games Daily", "slug": "kinda-funny-games-daily"},
    {"id": 479, "title": "Cozy Couch", "slug": "cozy-couch"},
    {"id": 478, "title": "How Hard Could it Be?", "slug": "how-hard-could-it-be"},
    {"id": 29, "title": "RTX", "slug": "rtx"},
    {"id": 275, "title": "Screencast", "slug": "screencast"},
    {"id": 272, "title": "Kinda Funny Podcast", "slug": "kinda-funny-podcast"},
    {
        "id": 435,
        "title": "Every Ninja Turtles Movie Ranked, Reviewed, & Recapped",
        "slug": "every-ninja-turtles-movie-ranked-reviewed-recapped",
    },
    {"id": 119, "title": "Fullhaus", "slug": "fullhaus"},
    {"id": 476, "title": "Let's Blend", "slug": "let-s-blend"},
    {
        "id": 477,
        "title": "Rooster Teeth Celebrates 20 Years of Making Fun",
        "slug": "rooster-teeth-celebrates-20-years-of-making-fun",
    },
    {
        "id": 480,
        "title": "Red vs. Blue: Restoration",
        "slug": "red-vs-blue-restoration",
    },
    {"id": 385, "title": "Kinda Funny Xcast", "slug": "kinda-funny-xcast"},
    {"id": 54, "title": "Lazer Team", "slug": "lazer-team"},
    {
        "id": 463,
        "title": "State Farm Gamerhood Challenge",
        "slug": "state-farm-gamerhood-challenge",
    },
    {"id": 255, "title": "Kinda Funny Gamescast", "slug": "kinda-funny-gamescast"},
    {"id": 342, "title": "Black Box Down", "slug": "black-box-down"},
    {"id": 19, "title": "RT Animated Adventures", "slug": "rt-animated-adventures"},
    {"id": 21, "title": "RT Life", "slug": "rt-life"},
    {"id": 430, "title": "Annual Pass", "slug": "annual-pass"},
    {
        "id": 336,
        "title": "Achievement Hunter Stream Archive",
        "slug": "achievement-hunter-stream-archive",
    },
    {
        "id": 193,
        "title": "Rooster Teeth Podcast Post Show",
        "slug": "rooster-teeth-podcast-post-show",
    },
    {
        "id": 453,
        "title": "Ship Hits the Fan Podcast",
        "slug": "ship-hits-the-fan-podcast",
    },
    {"id": 329, "title": "Let's Play Gmod", "slug": "let-s-play-gmod"},
    {"id": 335, "title": "PS I Love You XOXO", "slug": "ps-i-love-you-xoxo"},
    {
        "id": 470,
        "title": "F**KFACE Regulation Animation",
        "slug": "f-kface-regulation-animation",
    },
    {
        "id": 276,
        "title": "Every Marvel Cinematic Universe Movie Reviewed & Ranked",
        "slug": "every-marvel-cinematic-universe-movie-reviewed-ranked",
    },
    {"id": 300, "title": "Kinda Funny In Review", "slug": "kinda-funny-in-review"},
    {"id": 423, "title": "Black Heritage Month", "slug": "black-heritage-month"},
    {"id": 473, "title": "STF Sketches", "slug": "stf-sketches"},
    {
        "id": 338,
        "title": "Every DC Extended Universe movie reviewed & ranked",
        "slug": "every-dc-extended-universe-movie-reviewed-ranked",
    },
    {"id": 357, "title": "STF Gaming", "slug": "squad-team-force-streams"},
    {"id": 343, "title": "Easy Allies Podcast", "slug": "easy-allies-podcast"},
    {"id": 461, "title": "Kinda Funny Gameplay", "slug": "kinda-funny-gameplay"},
    {"id": 472, "title": "BENEATH", "slug": "beneath"},
    {"id": 471, "title": "Face Jam's Truck'd Up!", "slug": "face-jam-s-truck-d-up"},
    {"id": 436, "title": "Red vs. Blue Complete", "slug": "red-vs-blue-complete"},
    {"id": 289, "title": "Let's Play Minecraft", "slug": "let-s-play-minecraft"},
    {"id": 465, "title": "RWBY: Ice Queendom", "slug": "rwby-ice-queendom"},
    {"id": 175, "title": "RT Extras", "slug": "rt-extras"},
    {"id": 315, "title": "Google Trends", "slug": "google-trends"},
    {"id": 417, "title": "Community and Coffee", "slug": "community-and-coffee"},
    {"id": 205, "title": "Red vs. Blue PSA", "slug": "red-vs-blue-psa"},
    {"id": 455, "title": "Survive Block Island", "slug": "survive-block-island"},
    {"id": 384, "title": "Funhaus Plays GTA 5", "slug": "funhaus-plays-gta-5"},
    {"id": 360, "title": "TTT", "slug": "ttt"},
    {"id": 361, "title": "Simon's Peculiar Portions", "slug": "peculiar-portions"},
    {"id": 209, "title": "Overwatch Songs", "slug": "overwatch-songs"},
    {"id": 326, "title": "Star Wars In Review", "slug": "star-wars-in-review"},
    {"id": 468, "title": "UNO: Infinite", "slug": "uno-infinite"},
    {
        "id": 375,
        "title": "Every Kevin Smith Movie Reviewed & Ranked",
        "slug": "every-kevin-smith-movie-reviewed-ranked",
    },
    {
        "id": 410,
        "title": "Every Karate Kid Movie Reviewed & Ranked",
        "slug": "every-karate-kid-movie-reviewed-ranked",
    },
    {"id": 259, "title": "Kinda Funny Live Reactions", "slug": "live-reactions"},
    {"id": 271, "title": "Kinda Funny Live", "slug": "kinda-funny-live"},
    {"id": 84, "title": "Trailers", "slug": "trailers"},
    {
        "id": 466,
        "title": "Hardcore Tabletop Presents: The Red Dragon Inn",
        "slug": "hardcore-tabletop-presents-the-red-dragon-inn",
    },
    {"id": 110, "title": "Desk of DEATH BATTLE", "slug": "desk-of-death-battle"},
    {"id": 429, "title": "Face Jam Animated", "slug": "face-jam-animated"},
    {"id": 464, "title": "D&D, But...", "slug": "d-d-but"},
    {"id": 317, "title": "Ready Set Show", "slug": "ready-set-show"},
    {"id": 65, "title": "Open Haus", "slug": "open-haus"},
    {"id": 215, "title": "Rap Battles", "slug": "rap-battles"},
    {
        "id": 451,
        "title": "Achievement Hunter Wrestling",
        "slug": "achievement-hunter-wrestling",
    },
    {"id": 432, "title": "OT3 Podcast", "slug": "ot3-podcast"},
    {"id": 459, "title": "Red Web Animated", "slug": "red-web-animated"},
    {"id": 367, "title": "Talk CRWBY to Me", "slug": "talk-crwby-to-me"},
    {"id": 413, "title": "The Ship-it Show", "slug": "the-ship-it-show"},
    {"id": 454, "title": "Rooster Teeth Backstage", "slug": "rooster-teeth-backstage"},
    {
        "id": 304,
        "title": "Every Pixar Movie Reviewed and Ranked",
        "slug": "every-pixar-movie-reviewed-and-ranked",
    },
    {"id": 356, "title": "Hard Mode", "slug": "hard-mode"},
    {"id": 400, "title": "Model Employees", "slug": "model-employees"},
    {"id": 402, "title": "Comics Experiment", "slug": "comics-experiment"},
    {
        "id": 261,
        "title": "Every Spider-Man Movie Reviewed & Ranked",
        "slug": "every-spider-man-movie-reviewed-ranked",
    },
    {"id": 418, "title": "The Most", "slug": "the-most"},
    {"id": 59, "title": "RT Shorts", "slug": "rt-shorts"},
    {"id": 458, "title": "Improv Ambush", "slug": "improv-ambush"},
    {"id": 233, "title": "gen:LOCK", "slug": "gen-lock"},
    {"id": 427, "title": "Select All Gaming", "slug": "select-all-gaming"},
    {"id": 309, "title": "Let's Play GTA V", "slug": "let-s-play-gta-v"},
    {"id": 301, "title": "Murder Room", "slug": "murder-room"},
    {"id": 396, "title": "Castle Super Beast", "slug": "castle-super-beast"},
    {"id": 403, "title": "Podcast But Outside", "slug": "podcast-but-outside"},
    {"id": 399, "title": "Stay Zen", "slug": "stay-zen"},
    {"id": 185, "title": "Let's Watch", "slug": "let-s-watch"},
    {"id": 251, "title": "CypherDen's Adventures", "slug": "cypherden-s-adventures"},
    {"id": 412, "title": "Complete Story", "slug": "complete-story"},
    {
        "id": 440,
        "title": "Red vs. Blue: Family Shatters",
        "slug": "red-vs-blue-family-shatters",
    },
    {
        "id": 450,
        "title": "Black Box Down Aviation Explanation",
        "slug": "black-box-down-aviation-explanation",
    },
    {"id": 449, "title": "un:LOCKED", "slug": "un-locked"},
    {"id": 210, "title": "Halo Songs", "slug": "halo-songs"},
    {"id": 325, "title": "Good Morning From Hell", "slug": "good-morning-from-hell"},
    {"id": 448, "title": "RWBY: Fairy Tales", "slug": "rwby-fairy-tales"},
    {"id": 422, "title": "Why We're Going to Hell", "slug": "why-we-re-going-to-hell"},
    {"id": 371, "title": "Role Initiative", "slug": "role-initiative"},
    {
        "id": 425,
        "title": "Every Edgar Wright Movie Reviewed & Ranked",
        "slug": "every-edgar-wright-movie-reviewed-ranked",
    },
    {
        "id": 392,
        "title": "The Stuff Dreams Are Made Of",
        "slug": "the-stuff-dreams-are-made-of",
    },
    {"id": 344, "title": "Last Laugh", "slug": "last-laugh"},
    {"id": 346, "title": "Mysterious Monsters", "slug": "mysterious-monsters"},
    {"id": 138, "title": "Filmhaus Podcast", "slug": "filmhaus-podcast"},
    {"id": 331, "title": "CHUMP: Chump Change", "slug": "chump-post-show"},
    {"id": 330, "title": "CHUMP", "slug": "chump"},
    {"id": 437, "title": "Camp Betrayal", "slug": "camp-betrayal"},
    {"id": 10, "title": "AHWU", "slug": "ahwu"},
    {"id": 121, "title": "DBX", "slug": "dbx"},
    {"id": 419, "title": "The Real Canon", "slug": "the-real-canon"},
    {
        "id": 408,
        "title": "J vs Ben by the Super Carlin Brothers",
        "slug": "j-vs-ben-by-the-super-carlin-brothers",
    },
    {
        "id": 404,
        "title": "Harry Potter by the Super Carlin Brothers",
        "slug": "harry-potter-by-the-super-carlin-brothers",
    },
    {"id": 387, "title": "RWBY: The Grimm Campaign", "slug": "rwby-the-grimm-campaign"},
    {
        "id": 421,
        "title": "No Dumb Answers with Mark & Brad",
        "slug": "no-dumb-answers-with-mark-brad",
    },
    {"id": 415, "title": "Wrestling With The Week", "slug": "wrestling-with-the-week"},
    {"id": 433, "title": "Neon Konbini", "slug": "neon-konbini"},
    {"id": 364, "title": "Triforce", "slug": "triforce"},
    {
        "id": 391,
        "title": "Every Conjuring Cinematic Universe Movie Reviewed and Ranked",
        "slug": "every-conjuring-cinematic-universe-movie-reviewed-and-ranked",
    },
    {"id": 398, "title": "Cult Podcast", "slug": "cult-podcast"},
    {"id": 428, "title": "Select All Kickback", "slug": "select-all-kickback"},
    {"id": 148, "title": "RouLetsPlay", "slug": "rou-lets-play"},
    {
        "id": 386,
        "title": "Kinda Funny First Impressions",
        "slug": "kinda-funny-first-impressions",
    },
    {"id": 389, "title": "What's Good Games", "slug": "whatsgoodgames"},
    {"id": 347, "title": "Frame Trap", "slug": "frame-trap"},
    {
        "id": 407,
        "title": "Star Wars by the Super Carlin Brothers",
        "slug": "star-wars-by-the-super-carlin-brothers",
    },
    {
        "id": 405,
        "title": "Disney and Pixar by the Super Carlin Brothers",
        "slug": "disney-and-pixar-by-the-super-carlin-brothers",
    },
    {"id": 200, "title": "Death Battle Cast: Sudden Death", "slug": "sudden-death"},
    {"id": 354, "title": "I Have Notes", "slug": "i-have-notes"},
    {"id": 374, "title": "RT D&D", "slug": "rt-dd"},
    {"id": 332, "title": "This Just Internet", "slug": "this-just-internet"},
    {
        "id": 426,
        "title": "Every Monsterverse Movie Ranked & Reviewed",
        "slug": "every-monsterverse-movie-ranked-reviewed",
    },
    {"id": 33, "title": "RWBY", "slug": "rwby"},
    {"id": 359, "title": "GMOD Sandbox", "slug": "gmod-sandbox"},
    {
        "id": 406,
        "title": "Marvel by the Super Carlin Brothers",
        "slug": "marvel-by-the-super-carlin-brothers",
    },
    {
        "id": 424,
        "title": "Every John Wick Movie Reviewed & Ranked",
        "slug": "every-john-wick-movie-reviewed-ranked",
    },
    {"id": 414, "title": "Dead Little Roosters", "slug": "dead-little-roosters"},
    {
        "id": 420,
        "title": "Every Indiana Jones Movie Reviewed & Ranked",
        "slug": "every-indiana-jones-movie-reviewed-ranked",
    },
    {"id": 341, "title": "Anim Jam", "slug": "anim-jam"},
    {"id": 146, "title": "Backwardz Compatible", "slug": "backwardz-compatible"},
    {"id": 447, "title": "Red vs. Blue: Zero", "slug": "zero"},
    {
        "id": 378,
        "title": "F-ing Around with Ify and Fiona",
        "slug": "f-ing-around-with-ify-and-fiona",
    },
    {"id": 358, "title": "Select All", "slug": "select-all"},
    {
        "id": 382,
        "title": "Every Christopher Nolan Movie Reviewed & Ranked",
        "slug": "every-christopher-nolan-movie-reviewed-ranked",
    },
    {"id": 262, "title": "Internet Explorerz", "slug": "internet-explorerz"},
    {"id": 303, "title": "We Have Cool Friends", "slug": "we-have-cool-friends"},
    {
        "id": 411,
        "title": "Comicstorian Rants and Reviews",
        "slug": "comicstorian-rants-and-reviews",
    },
    {"id": 377, "title": "Keeping the Lights On", "slug": "keeping-the-lights-on"},
    {"id": 278, "title": "Kinda Funny AF", "slug": "kinda-funny-af"},
    {"id": 365, "title": "High Rollers: Aerois", "slug": "high-rollers-aerois"},
    {
        "id": 388,
        "title": "Every Batman Movie Reviewed and Ranked",
        "slug": "every-batman-movie-reviewed-and-ranked",
    },
    {"id": 192, "title": "Master and Apprentice", "slug": "master-and-apprentice"},
    {
        "id": 383,
        "title": "Every Studio Ghibli Movie Reviewed and Ranked",
        "slug": "every-studio-ghibli-movie-reviewed-and-ranked",
    },
    {"id": 368, "title": "Co-op Adventures!", "slug": "co-op-adventures"},
    {"id": 381, "title": "Recorded by Arizal", "slug": "recorded-by-arizal"},
    {"id": 366, "title": "Hardcore Mini Golf", "slug": "hardcore-mini-golf"},
    {"id": 380, "title": "Death Race", "slug": "death-race"},
    {"id": 322, "title": "Morning Haus", "slug": "morning-haus"},
    {
        "id": 372,
        "title": "Every Lord of the Rings Movie Reviewed & Ranked",
        "slug": "every-lord-of-the-rings-movie-reviewed-ranked",
    },
    {"id": 376, "title": "Doom Patrol", "slug": "doom-patrol"},
    {
        "id": 373,
        "title": "Every Star Trek Movie Reviewed & Ranked",
        "slug": "every-star-trek-movie-reviewed-ranked",
    },
    {"id": 334, "title": "RT Inbox", "slug": "rt-inbox"},
    {
        "id": 370,
        "title": "Every Transformers Movie Reviewed & Ranked",
        "slug": "every-transformers-movie-reviewed-ranked",
    },
    {"id": 191, "title": "Always Open: Still Open", "slug": "still-open"},
    {"id": 348, "title": "Box Peek", "slug": "box-peek"},
    {"id": 340, "title": "No Idea", "slug": "no-idea-ikea"},
    {"id": 187, "title": "Beyond the Pine", "slug": "beyond-the-pine"},
    {"id": 363, "title": "Hat Films", "slug": "hat-films"},
    {"id": 135, "title": "Crunch Time", "slug": "crunch-time"},
    {"id": 345, "title": "7 Wonderings", "slug": "7-wonderings"},
    {"id": 64, "title": "Demo Disk", "slug": "demo-disk"},
    {"id": 362, "title": "Hat Chat", "slug": "hat-chat"},
    {
        "id": 263,
        "title": "Kinda Funny: The Animated Series",
        "slug": "kinda-funny-the-animated-series",
    },
    {"id": 89, "title": "In Review", "slug": "in-review"},
    {"id": 350, "title": "Achieve It Yourself!", "slug": "achieve-it-yourself"},
    {"id": 267, "title": "Kinda Funny Doodles", "slug": "kinda-funny-doodles"},
    {"id": 153, "title": "VR the Champions", "slug": "vr-the-champions"},
    {"id": 236, "title": "Haunter", "slug": "achievement-haunter"},
    {"id": 38, "title": "VS", "slug": "vs"},
    {"id": 117, "title": "Fan Service", "slug": "fan-service"},
    {"id": 14, "title": "Achievement HORSE", "slug": "achievement-horse"},
    {"id": 11, "title": "Fails of the Weak", "slug": "fails-of-the-weak"},
    {"id": 128, "title": "Cow Chop", "slug": "cow-chop"},
    {"id": 171, "title": "CCTV", "slug": "cctv"},
    {"id": 50, "title": "Minimations", "slug": "minimations"},
    {"id": 314, "title": "YOUR SHOW", "slug": "it-s-your-show"},
    {"id": 231, "title": "Arizona Circle", "slug": "arizona-circle"},
    {"id": 24, "title": "Things to Do In", "slug": "things-to-do-in"},
    {"id": 306, "title": "RT Twitch", "slug": "rt-twitch"},
    {"id": 320, "title": "RWBY Complete", "slug": "rwby-complete"},
    {"id": 321, "title": "Trivia Bidet", "slug": "trivia-bidet"},
    {"id": 130, "title": "Day 5", "slug": "day5"},
    {"id": 194, "title": "On the Spot: For The Win", "slug": "for-the-win"},
    {
        "id": 310,
        "title": "Every Harry Potter Movie Reviewed & Ranked",
        "slug": "every-harry-potter-movie-reviewed-ranked",
    },
    {"id": 156, "title": "Cow Chop Gaming", "slug": "cow-chop-gaming"},
    {"id": 159, "title": "Behind the Cow Chop", "slug": "behind-the-cow-chop"},
    {"id": 234, "title": "Game Time", "slug": "game-time"},
    {"id": 252, "title": "Party Mode", "slug": "party-mode"},
    {"id": 157, "title": "Wrong Side of YouTube", "slug": "wrong-side-of-you-tube"},
    {"id": 313, "title": "Vicious Circle", "slug": "vicious-circle"},
    {"id": 151, "title": "Shenanigans", "slug": "shenanigans"},
    {"id": 305, "title": "Get Fact", "slug": "get-fact"},
    {"id": 264, "title": "Nick Names", "slug": "nick-names"},
    {"id": 244, "title": "Top 10", "slug": "top-10"},
    {
        "id": 270,
        "title": "Every Fast and Furious Movie Reviewed & Ranked",
        "slug": "every-fast-and-furious-movie-reviewed-ranked",
    },
    {"id": 16, "title": "Rage Quit", "slug": "rage-quit"},
    {
        "id": 266,
        "title": "Every X-Men Movie Reviewed & Ranked",
        "slug": "every-x-men-movie-reviewed-ranked",
    },
    {
        "id": 302,
        "title": "Murder Room: After The Verdict",
        "slug": "murder-room-after-the-verdict",
    },
    {"id": 216, "title": "JT Music Raps LIVE", "slug": "jt-music-raps-live"},
    {"id": 188, "title": "Alternative Lifestyle", "slug": "alternative-lifestyle"},
    {"id": 294, "title": "KF Vlogs", "slug": "kf-vlogs"},
    {"id": 260, "title": "Cooking With Greggy", "slug": "cooking-with-greggy"},
    {
        "id": 446,
        "title": "Red vs. Blue: The Shisno Trilogy",
        "slug": "the-shisno-trilogy",
    },
    {"id": 230, "title": "Hardcore Tabletop", "slug": "hardcore-tabletop"},
    {
        "id": 297,
        "title": "Game of Thrones Final Season In Review",
        "slug": "game-of-thrones-final-season-in-review",
    },
    {"id": 288, "title": "Live from WZRD", "slug": "live-from-wzrd"},
    {"id": 67, "title": "Dude Soup Post Show", "slug": "fan-show"},
    {"id": 160, "title": "Foreign Import", "slug": "foreign-import"},
    {"id": 281, "title": "Roasted", "slug": "roasted"},
    {
        "id": 295,
        "title": "Halo 4: Forward Unto Dawn",
        "slug": "halo-4-forward-unto-dawn",
    },
    {
        "id": 287,
        "title": "Every Mission: Impossible movie reviewed & ranked",
        "slug": "every-mission-impossible-movie-reviewed-ranked",
    },
    {"id": 265, "title": "Love & Sex Stuff", "slug": "love-sex-stuff"},
    {"id": 158, "title": "Amazon Prime Time", "slug": "amazon-prime-time"},
    {"id": 268, "title": "Debatable", "slug": "debatable"},
    {
        "id": 290,
        "title": "Assassin's Creed Musical",
        "slug": "assassin-s-creed-musical",
    },
    {"id": 292, "title": "Minecraft Horror Story", "slug": "minecraft-horror-story"},
    {"id": 293, "title": "Titanfall Dropouts", "slug": "titanfall-dropouts"},
    {"id": 246, "title": "The Weird Place", "slug": "the-weird-place"},
    {"id": 85, "title": "RT Docs", "slug": "rt-docs"},
    {"id": 235, "title": "Gaming Weekly", "slug": "gaming-weekly"},
    {"id": 190, "title": "Bloopers", "slug": "bloopers"},
    {"id": 243, "title": "That Sketch", "slug": "that-sketch"},
    {"id": 283, "title": "Boss Battles", "slug": "boss-battles"},
    {"id": 282, "title": "Cheap Game / Cheap Life", "slug": "cheap-game-cheap-life"},
    {"id": 242, "title": "Music Videos", "slug": "sp7-music-videos"},
    {
        "id": 286,
        "title": "All Your History Are Belong To Us",
        "slug": "all-your-history-are-belong-to-us",
    },
    {"id": 245, "title": "Blood Fest", "slug": "blood-fest"},
    {"id": 55, "title": "Achievement Unlocked", "slug": "achievement-unlocked"},
    {"id": 284, "title": "Transformers", "slug": "transformers"},
    {"id": 166, "title": "Glitch Please", "slug": "glitch-please"},
    {"id": 196, "title": "Glitch Please: New Game +", "slug": "new-game"},
    {
        "id": 183,
        "title": "CRWBY: Behind the Episode",
        "slug": "c-r-w-b-y-behind-the-episode",
    },
    {"id": 182, "title": "RWBY Rewind", "slug": "rwby-rewind"},
    {"id": 258, "title": "The PlayStation VR Show", "slug": "the-playstation-vr-show"},
    {"id": 75, "title": "Game News", "slug": "game-news"},
    {"id": 101, "title": "ScrewAttack Presents: Top 10", "slug": "top-10s"},
    {"id": 223, "title": "Photoshop Battles", "slug": "photoshop-battles"},
    {"id": 239, "title": "What Do You Know", "slug": "what-do-you-know"},
    {"id": 56, "title": "Easter Eggs", "slug": "easter-eggs"},
    {"id": 232, "title": "Club Club", "slug": "club-club"},
    {"id": 73, "title": "Million Dollars, But...", "slug": "million-dollars-but"},
    {
        "id": 240,
        "title": "The Mind of Steven Suptic",
        "slug": "the-mind-of-steven-suptic",
    },
    {
        "id": 238,
        "title": "The Bungalow: The Business of Rooster Teeth",
        "slug": "the-bungalow",
    },
    {"id": 241, "title": "GORQ's Quest", "slug": "gorq-s-quest"},
    {"id": 83, "title": "Sportsball", "slug": "sportsball"},
    {"id": 76, "title": "Entertainment News", "slug": "entertainment-news"},
    {"id": 162, "title": "Cow Chop VR", "slug": "cow-chop-vr"},
    {"id": 222, "title": "Nomad of Nowhere", "slug": "nomad-of-nowhere"},
    {"id": 125, "title": "RWBY Chibi", "slug": "rwby-chibi"},
    {"id": 131, "title": "Heroes & Halfwits", "slug": "heroes-halfwits"},
    {"id": 207, "title": "GUINNESS WORLD RECORDS", "slug": "guinness-world-records"},
    {
        "id": 198,
        "title": "Heroes & Halfwits Post Show",
        "slug": "heroes-halfwits-post-show",
    },
    {"id": 79, "title": "Specials", "slug": "specials"},
    {"id": 68, "title": "Pilot Program", "slug": "pilot-program"},
    {"id": 77, "title": "Tech and Science News", "slug": "tech-and-science-news"},
    {"id": 220, "title": "Lifestyle Classic", "slug": "lifestyle-classic"},
    {"id": 170, "title": "Class Of 198X", "slug": "class-of-198-x"},
    {
        "id": 443,
        "title": "Red vs. Blue: Project Freelancer Saga",
        "slug": "project-freelancer-saga",
    },
    {"id": 214, "title": "Minecraft Songs", "slug": "minecraft-songs"},
    {
        "id": 212,
        "title": "JT Music Behind the Scenes",
        "slug": "jt-music-behind-the-scenes",
    },
    {"id": 178, "title": "ESPORTS EJECTS", "slug": "esports-ejects"},
    {"id": 165, "title": "RT Podcast Let's Play", "slug": "rt-podcast-let-s-play"},
    {"id": 176, "title": "Burnie Vlog", "slug": "burnie-vlog"},
    {
        "id": 180,
        "title": "Twits and Crits: The League of Extraordinary Jiremen",
        "slug": "the-league-of-extraordinary-jiremen",
    },
    {"id": 139, "title": "Past Livestreams", "slug": "past-livestreams"},
    {"id": 161, "title": "Retroactive", "slug": "retroactive"},
    {"id": 189, "title": "Let's Pine", "slug": "let-s-pine"},
    {"id": 82, "title": "Music Videos", "slug": "music-videos"},
    {"id": 186, "title": "The Woods", "slug": "the-woods"},
    {"id": 35, "title": "The Slow Mo Guys", "slug": "the-slow-mo-guys"},
    {"id": 134, "title": "Twits and Crits", "slug": "twits-crits"},
    {
        "id": 177,
        "title": "Tuesday Night Game Fight",
        "slug": "tuesday-night-game-fight",
    },
    {
        "id": 202,
        "title": "Tuesday Night Game Fight: Post Fight Battle",
        "slug": "post-fight-battle",
    },
    {"id": 179, "title": "Know Your Thrones", "slug": "know-your-thrones"},
    {"id": 168, "title": "Barbara Vlogs", "slug": "barbara-vlogs"},
    {"id": 155, "title": "Relationship Goals", "slug": "relationship-goals"},
    {"id": 9, "title": "Immersion", "slug": "immersion"},
    {"id": 167, "title": "Schooled", "slug": "schooled"},
    {
        "id": 169,
        "title": "Let's Play Live: Life on Tour",
        "slug": "let-s-play-live-life-on-tour",
    },
    {"id": 150, "title": "Enjoy the Show", "slug": "enjoy-the-show"},
    {"id": 154, "title": "A Spot of Science", "slug": "a-spot-of-science"},
    {
        "id": 203,
        "title": "Enjoy the Show: After The Credits",
        "slug": "after-the-credits",
    },
    {"id": 133, "title": "Sex Swing", "slug": "sex-swing"},
    {
        "id": 149,
        "title": "The Eleven Little Roosters",
        "slug": "eleven-little-roosters",
    },
    {"id": 97, "title": "Random Awesomeness", "slug": "random-awesomeness"},
    {"id": 147, "title": "Let Me Clarify", "slug": "let-me-clarify"},
    {"id": 390, "title": "RWBY: World of Remnant", "slug": "world-of-remnant"},
    {"id": 70, "title": "The Patch", "slug": "the-patch"},
    {"id": 90, "title": "FIRST Member Vlog", "slug": "sponsor-vlog"},
    {"id": 445, "title": "Red vs. Blue: Anthology", "slug": "anthology"},
    {"id": 98, "title": "SideScrollers Podcast", "slug": "sidescrollers"},
    {"id": 123, "title": "Available Now Podcast", "slug": "available-now-podcast"},
    {"id": 60, "title": "The Patch Game Club", "slug": "the-patch-game-club"},
    {"id": 112, "title": "Who is", "slug": "who-is"},
    {"id": 40, "title": "GO!", "slug": "go"},
    {"id": 126, "title": "ScrewAttack Illustrated", "slug": "screw-attack-illustrated"},
    {"id": 102, "title": "Video Game Vault", "slug": "video-game-vault"},
    {"id": 42, "title": "RT Sponsor Cut", "slug": "rt-sponsor-cut"},
    {"id": 93, "title": "ScrewAttack Shorts", "slug": "clip-of-the-week"},
    {"id": 92, "title": "RT Specials", "slug": "rt-specials"},
    {"id": 36, "title": "Five Facts", "slug": "five-facts"},
    {"id": 61, "title": "How To", "slug": "how-to"},
    {"id": 39, "title": "Achievement HUNT", "slug": "achievement-hunt"},
    {"id": 49, "title": "Happy Hour", "slug": "happy-hour"},
    {"id": 108, "title": "Five Fun Facts", "slug": "five-fun-facts"},
    {"id": 122, "title": "The #1 Show", "slug": "the-1-show"},
    {"id": 106, "title": "Evil Craig", "slug": "evil-craig"},
    {"id": 115, "title": "Reasons We Love", "slug": "reasons-we-love"},
    {"id": 100, "title": "The Best Ever", "slug": "the-best-ever"},
    {"id": 88, "title": "Buff Buddies", "slug": "buff-buddies"},
    {"id": 113, "title": "Is it Good", "slug": "is-it-good"},
    {"id": 44, "title": "Countdown", "slug": "countdown"},
    {"id": 109, "title": "One Minute Melee", "slug": "one-minute-melee"},
    {"id": 52, "title": "X-Ray and Vav", "slug": "x-ray-and-vav"},
    {"id": 48, "title": "Social Disorder", "slug": "social-disorder"},
    {"id": 86, "title": "RTES", "slug": "rtes"},
    {"id": 116, "title": "The Industry", "slug": "the-industry"},
    {
        "id": 72,
        "title": "FAQ Podcast [Funhaus Answers Questions]",
        "slug": "faq-podcast-funhaus-answers-questions",
    },
    {"id": 2, "title": "The Strangerhood", "slug": "the-strangerhood"},
    {
        "id": 444,
        "title": "Red vs. Blue: The Chorus Trilogy",
        "slug": "the-chorus-trilogy",
    },
    {"id": 17, "title": "This is...", "slug": "this-is"},
    {"id": 46, "title": "MegaCraft", "slug": "megacraft"},
    {"id": 57, "title": "Sunday Driving", "slug": "sunday-driving"},
    {"id": 58, "title": "RT Showcase", "slug": "rt-showcase"},
    {
        "id": 111,
        "title": "Great Moments in Video Game History",
        "slug": "great-moments-in-video-game-history",
    },
    {"id": 45, "title": "Imaginary Achievements", "slug": "imaginary-achievements"},
    {"id": 51, "title": "Ten Little Roosters", "slug": "ten-little-roosters"},
    {"id": 95, "title": "Hard News", "slug": "hard-news"},
    {"id": 26, "title": "Trials Files", "slug": "trials-files"},
    {"id": 71, "title": "Screen Play", "slug": "screen-play"},
    {"id": 96, "title": "Out of the Box", "slug": "out-of-the-box"},
    {"id": 18, "title": "Game Fails", "slug": "game-fails"},
    {"id": 41, "title": "RT News", "slug": "rt-news"},
    {"id": 32, "title": "The Gauntlet", "slug": "the-gauntlet"},
    {"id": 99, "title": "The Armory", "slug": "the-armory"},
    {"id": 107, "title": "Nerdtastic", "slug": "nerdtastic"},
    {"id": 31, "title": "Trials Pig", "slug": "trials-pig"},
    {"id": 30, "title": "Quick Bits", "slug": "quick-bits"},
    {"id": 105, "title": "Newsroom", "slug": "newsroom"},
    {"id": 27, "title": "Nature Town", "slug": "nature-town"},
    {"id": 25, "title": "A Look Back At", "slug": "a-look-back-at"},
    {"id": 23, "title": "AH Predicts", "slug": "ah-predicts"},
    {"id": 20, "title": "Past Cast", "slug": "past-cast"},
    {"id": 104, "title": "Metal Gear Ben", "slug": "metal-gear-ben"},
    {"id": 103, "title": "Reboot or Retro", "slug": "reboot-or-retro"},
    {"id": 15, "title": "Drunk Tank", "slug": "drunk-tank"},
    {"id": 442, "title": "Red vs. Blue: The Recollection", "slug": "the-recollection"},
    {"id": 12, "title": "Pajamachievements", "slug": "pajamachievements"},
    {"id": 7, "title": "Captain Dynamic", "slug": "captain-dynamic"},
    {"id": 8, "title": "Stroyent", "slug": "stroyent"},
    {
        "id": 441,
        "title": "Red vs. Blue: Blood Gulch Chronicles",
        "slug": "blood-gulch-chronicles",
    },
    {"id": 4, "title": "1-800-Magic", "slug": "1-800-magic"},
    {"id": 3, "title": "PANICS", "slug": "panics"},
]


def get_show_name_from_id(show_id):
    for show in shows:
        if "uuid" in show and show["uuid"] == show_id:
            return show["title"]
    return None
