name: Fetch updated links every half hour - urls

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Save print statements to README and commit changes
      run: |
        echo "Print statements from the latest run:" > README.md
        python main.py >> README.md
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add README.md
        git commit -m "Update README with print statements"
        git push

