name: Fetch updated links hourly

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run Python script
      run: python main.py

    - name: Save output to README
      run: echo "Print statements from the latest run:" > README.md && python main.py >> README.md
